[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache'


[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"
metis = "${METIS_RPC}"
